Add article category
Mental-Health-Charity/MentalHealthCharity-backend pull request #7
Opened 2023-08-06 17:04 UTC by mrdartmoor

2023-08-07 19:49 UTC, BartekDe requested changes

2023-08-07 19:49 UTC, BartekDe commented on app/api/api_v1/endpoints/article.py
> +    current_user=Depends(deps.get_current_active_user),
teraz zwykli użytkownicy też mają móc dodawać artykuły?

2023-08-07 19:49 UTC, BartekDe commented on app/api/api_v1/endpoints/article.py
> +    current_user=Depends(deps.get_current_active_admin_user),
jeśli zwykli użytkownicy mają móc dodawać artykuły to raczej dajmy im możliwość usunięcia ich własnego artykułu

2023-08-07 19:49 UTC, BartekDe commented on app/api/api_v1/endpoints/article.py
> +    current_user=Depends(deps.get_current_active_admin_user),
i w takim przypadku musimy dodać zabezpieczenie, żeby można było usuwać tylko swoje artykuły, chyba że jest się adminem

2023-08-07 20:04 UTC, mrdartmoor commented on app/api/api_v1/endpoints/article.py
> +    current_user=Depends(deps.get_current_active_user),
hmyy w sumie to wolontariusze mogą albo admini. Zrobić ifa?

2023-08-08 14:09 UTC, mrdartmoor commented on app/api/api_v1/endpoints/article.py
> +    current_user=Depends(deps.get_current_active_admin_user),
Dodałem

2023-08-08 17:56 UTC, BartekDe commented on app/api/api_v1/endpoints/article.py
> +    article_category = crud.article_category.get(db, id=article_in.article_category_id)
tutaj też musimy się upewnić, że użytkownik może edytować tylko swój artykuł (lub jeśli jest adminem to może wszystkie), wydaje mi się, że wystarczy dodać to samo co przy usuwaniu:
```suggestion
    article_category = crud.article_category.get(db, id=article_in.article_category_id)
    if article.created_by_id != current_user.id or current_user.user_role != UserRoleEnum.ADMIN:
        raise HTTPException(status_code=403, detail="Not enough permissions")
```

2023-08-08 19:10 UTC, mrdartmoor commented on app/api/api_v1/endpoints/article.py
> +    article_category = crud.article_category.get(db, id=article_in.article_category_id)
Dodane

2023-08-08 19:30 UTC, BartekDe approved these changes
wygląda git i widzę, że rozwiązałeś konflikty :) approved

2023-08-08 20:04 UTC, merged